// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25koEe5OPFCp9B8VbpAE9iLC52Zoo9Gk',
    appId: '1:1083797462241:android:2b2a8a02dbc6f33c616ba0',
    messagingSenderId: '1083797462241',
    projectId: 'bacpro-ba190',
    storageBucket: 'bacpro-ba190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0VsJ8lI6YeatLkgOG1qQt3lnYlNLJI8E',
    appId: '1:1083797462241:ios:e5bd5db8725893e0616ba0',
    messagingSenderId: '1083797462241',
    projectId: 'bacpro-ba190',
    storageBucket: 'bacpro-ba190.firebasestorage.app',
    iosClientId: '1083797462241-5grfjkje9gg9nqi7ltnb0goi9heekscv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0VsJ8lI6YeatLkgOG1qQt3lnYlNLJI8E',
    appId: '1:1083797462241:ios:e5bd5db8725893e0616ba0',
    messagingSenderId: '1083797462241',
    projectId: 'bacpro-ba190',
    storageBucket: 'bacpro-ba190.firebasestorage.app',
    iosClientId: '1083797462241-5grfjkje9gg9nqi7ltnb0goi9heekscv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacApp',
  );

}